#
# Makefile for stklos-gtk-glade example
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date:  8-Apr-2008 19:26 (eg)
# Last file update:  8-Apr-2008 19:27 (eg)

all: interface

interface: interface.stk 
	stklos-compile -o interface interface.stk

clean:
	/bin/rm -f interface *~ 
